chateau/feedback/forms.py
# Copyright 2021 Softwerks LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import flask_wtf
import wtforms
import wtforms.validators


class NPSForm(flask_wtf.FlaskForm):
    nps = wtforms.RadioField(
        label="How likely is it that you would recommend the Backgammon Network to a friend?",
        choices=[
            (1, "1"),
            (2, "2"),
            (3, "3"),
            (4, "4"),
            (5, "5"),
            (6, "6"),
            (7, "7"),
            (8, "8"),
            (9, "9"),
            (10, "10"),
        ],
        coerce=int,
        validators=[
            wtforms.validators.DataRequired(),
            wtforms.validators.NumberRange(1, 10),
        ],
    )
    comments = wtforms.TextAreaField(
        label="Any other feedback? (Optional)",
        validators=[wtforms.validators.Optional(), wtforms.validators.Length(max=511)],
    )

chateau/feedback/__init__.py
# Copyright 2021 Softwerks LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import flask

blueprint = flask.Blueprint("feedback", __name__)

import chateau.feedback.routes

chateau/feedback/routes.py
# Copyright 2021 Softwerks LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Tuple, Union
import urllib.parse

import flask
import flask_wtf
import werkzeug

from chateau import database
from chateau.feedback import blueprint
from chateau.feedback import forms


@blueprint.route("nps", methods=["GET", "POST"])
def nps() -> Union[werkzeug.wrappers.Response, str]:
    form: flask_wtf.FlaskForm = forms.NPSForm()

    if form.validate_on_submit():
        nps: int = form.nps.data
        comments: str = form.comments.data

        try:
            database.feedback.create(nps, comments)
        except database.DatabaseError:
            flask.abort(500)

        return flask.redirect(flask.url_for("index"))

    flask.g.session.update_feedback_timestamp()

    return flask.render_template("feedback/nps.html", form=form)

chateau/templates/feedback/nps.html
{% extends "base.html" %}

{% block description %}What do you think of the Backgammon Network?{% endblock %}

{% block title %}Feedback | {% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/feedback.css') }}" />
{% endblock %}

{% block content %}
<div class="feedback">
    <h1>Thanks for playing!</h1>
    <p>Before you go, please take a moment to tell me what you think of the Backgammon Network.</p>
    <form action="{{ url_for('feedback.nps') }}" method="post">
        {{ form.csrf_token }}
        {{ form.nps.label(class="question") }}
        <div class="nps">
            {% for subfield in form.nps %}
                <div>
                    {{ subfield(required=True) }}
                    <span>{{ subfield.label }}</span>
                </div>
            {% endfor %}
        </div>
        <div class="description">
            <span>Not at all likely</span>
            <span>Neutral</span>
            <span>Extremely likely</span>
        </div>
        {{ form.comments.label(class="question") }}
        {{ form.comments(cols="40", rows="5", maxlength="511") }}
        <button type="submit">Submit feedback</button>
    <form>
    <a href="{{ url_for('index') }}">Return to homepage</a>
</div>
{% endblock %}