chateau/stats/forms.py
# Copyright 2021 Softwerks LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from datetime import date

import flask_wtf
import wtforms
import wtforms.validators


class DetailsForm(flask_wtf.FlaskForm):
    date = wtforms.DateField(
        "Date", [wtforms.validators.DataRequired()], default=date.today()
    )

chateau/stats/__init__.py
# Copyright 2021 Softwerks LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from datetime import datetime, timedelta, timezone
from http import HTTPStatus
from typing import Optional
import time
import urllib.parse

import flask

import redis


blueprint = flask.Blueprint("stats", __name__)

import chateau.stats.routes


def init_app(app: flask.app.Flask) -> None:
    """Initialize the app."""
    app.before_request(_before)
    app.after_request(_after)


def _before() -> None:
    if "start" not in flask.g:
        flask.g.start = time.perf_counter()


def _after(response: flask.Response) -> flask.Response:
    if response.status_code < HTTPStatus.BAD_REQUEST:
        _store_stats()

    return response


def _store_stats() -> None:
    now: datetime = datetime.now(timezone.utc)
    date: str = now.strftime("%Y-%m-%d")
    expire: int = int(
        datetime.timestamp(
            now.replace(hour=0, minute=0, second=0, microsecond=0) + timedelta(days=30)
        )
    )

    url: urllib.parse.ParseResult = urllib.parse.urlparse(flask.request.url)

    pipeline: redis.client.Pipeline = flask.g.redis.pipeline()

    _store_page(pipeline, date, expire, url)
    _store_browser(pipeline, date, expire)
    _store_os(pipeline, date, expire)
    _store_referrer(pipeline, date, expire)
    _store_response_time(pipeline, url)
    _update_visitor_count(pipeline, date, expire)
    _update_page_views(pipeline, date, expire)

    pipeline.execute()


def _store_page(
    pipeline: redis.client.Pipeline,
    date: str,
    expire: int,
    url: urllib.parse.ParseResult,
) -> None:
    key: str = f"stats:page:{date}"
    pipeline.zincrby(key, 1, url.path)
    pipeline.expireat(key, expire)


def _store_browser(pipeline: redis.client.Pipeline, date: str, expire: int) -> None:
    browser: Optional[str] = flask.request.user_agent.browser
    if browser is not None:
        browser_key: str = f"stats:browser:{date}"
        pipeline.zincrby(browser_key, 1, browser)
        pipeline.expireat(browser_key, expire)

        version: Optional[str] = flask.request.user_agent.version
        if version is not None:
            version_key: str = f"stats:{browser}:{date}"
            pipeline.zincrby(version_key, 1, version)
            pipeline.expireat(version_key, expire)


def _store_os(pipeline: redis.client.Pipeline, date: str, expire: int) -> None:
    os: Optional[str] = flask.request.user_agent.platform
    if os is not None:
        key: str = f"stats:os:{date}"
        pipeline.zincrby(key, 1, os)
        pipeline.expireat(key, expire)


def _store_referrer(pipeline: redis.client.Pipeline, date: str, expire: int) -> None:
    referrer: Optional[str] = flask.request.referrer
    if referrer is not None:
        try:
            referrer_url: urllib.parse.ParseResult = urllib.parse.urlparse(
                flask.request.url
            )
        except:
            pass
        else:
            key: str = f"stats:referrers:{date}"
            pipeline.zincrby(key, 1, referrer_url.netloc)
            pipeline.expireat(key, expire)


def _store_response_time(
    pipeline: redis.client.Pipeline, url: urllib.parse.ParseResult
) -> None:
    response_time: float = round(time.perf_counter() - flask.g.start, 3)
    key: str = f"stats:perf:{url.path}"
    pipeline.lpush(key, response_time)
    pipeline.ltrim(key, 0, 99)


def _update_visitor_count(
    pipeline: redis.client.Pipeline, date: str, expire: int
) -> None:
    key: str = f"stats:visitors:{date}"
    pipeline.pfadd(key, flask.g.session.id_)
    pipeline.expire(key, expire)


def _update_page_views(pipeline: redis.client.Pipeline, date: str, expire: int) -> None:
    key: str = f"stats:views:{date}"
    pipeline.incr(key)
    pipeline.expire(key, expire)

chateau/stats/routes.py
# Copyright 2021 Softwerks LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from datetime import datetime, timezone
from typing import List, Tuple, Union

import flask
import flask_wtf
import werkzeug

from chateau.stats import blueprint
from chateau.stats import forms


@blueprint.route("", methods=["GET", "POST"])
def dashboard() -> Union[werkzeug.wrappers.Response, str]:
    form: flask_wtf.FlaskForm = forms.DetailsForm()

    if form.validate_on_submit():
        return flask.redirect(flask.url_for("stats.details", date=form.date.data))

    today: str = _today()
    connected: int = flask.g.redis.get("stats:connected")
    visitors: int = flask.g.redis.pfcount(f"stats:visitors:{today}")
    views: int = flask.g.redis.get(f"stats:views:{today}")

    return flask.render_template(
        "stats/dashboard.html",
        form=form,
        connected=connected,
        visitors=visitors,
        views=views,
    )


@blueprint.route("details")
def details() -> str:
    date: str = flask.request.args.get("date", _today())

    referrers: List[Tuple[str, float]] = flask.g.redis.zrange(
        f"stats:referrers:{date}", -10, -1, withscores=True
    )
    pages: List[Tuple[str, float]] = flask.g.redis.zrange(
        f"stats:page:{date}", -10, -1, withscores=True
    )
    browsers: List[Tuple[str, float]] = flask.g.redis.zrange(
        f"stats:browser:{date}", -10, -1, withscores=True
    )
    os: List[Tuple[str, float]] = flask.g.redis.zrange(
        f"stats:os:{date}", -10, -1, withscores=True
    )

    return flask.render_template(
        "stats/details.html",
        referrers=referrers,
        pages=pages,
        browsers=browsers,
        os=os,
    )


def _today() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")

chateau/templates/stats/dashboard.html
{% extends "base.html" %}

{% block description %}Backgammon Network stats.{% endblock %}

{% block title %}Stats | {% endblock %}

{% block content %}
<div>
    <h1>Current players</h1>
    <p>{{ connected }}</p>

    <h1>Unique visitors</h1>
    <p>{{ visitors }}</p>

    <h1>Page views</h1>
    <p>{{ views }}</p>

    <form action="{{ url_for('stats.dashboard') }}" method="post">
        {{ form.csrf_token }}
        {{ form.date(type="date") }}
        <div class="submit">
            <button type="submit">View details</button>
        </div>
    </form>
</div>
{% endblock %}

chateau/templates/stats/details.html
{% extends "base.html" %}

{% block description %}Backgammon Network detailed stats.{% endblock %}

{% block title %}Details | {% endblock %}

{% block content %}
<div>
    <h1>Referrer</h1>
    <table>
        <thead>
            <th>Source</th>
            <th>Count</th>
        </thead>
        {% for r in referrers|reverse %}
        <tr>
            <td><img src="https://icons.duckduckgo.com/ip3/{{ r[0] }}.ico" width="16" height="16">{{ r[0] }}</td>
            <td>{{ r[1]|int }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div>
    <h1>Page</h1>
    <table>
        <thead>
            <th>Page</th>
            <th>Views</th>
        </thead>
        {% for p in pages|reverse %}
        <tr>
            <td>{{ p[0] }}</td>
            <td>{{ p[1]|int }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div>
    <h1>Browser</h1>
    <table>
        <thead>
            <th>Browser</th>
            <th>Count</th>
        </thead>
        {% for b in browsers|reverse %}
        <tr>
            <td>{{ b[0]|title }}</td>
            <td>{{ b[1]|int }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div>
    <h1>Operating system</h1>
    <table>
        <thead>
            <th>OS</th>
            <th>Count</th>
        </thead>
        {% for o in os|reverse %}
        <tr>
            <td>{{ o[0]|title }}</td>
            <td>{{ o[1]|int }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}